[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 3000

[[services]]
  internal_port = 3005
  protocol = "tcp"

  [[services.ports]]
    port = 3005

[[services]]
  internal_port = 3010
  protocol = "tcp"

  [[services.ports]]
    port = 3010

[[services]]
  internal_port = 3015
  protocol = "tcp"

  [[services.ports]]
    port = 3015

# Had trouble with UDP on fly... so I spun up a
# DO Droplet instead for the first UDP challenge.
# [[services]]
#   internal_port = 3020
#   protocol = "udp"
#
#   [[services.ports]]
#     port = 3020

[[services]]
  internal_port = 3025
  protocol = "tcp"

  [[services.ports]]
    port = 3025
